### ISSUE TITLE
Can't get contrast in header

### ISSUE THREAD

**Issue by tchi0007** [tchi0007/kraken-good-accessibility#1]
Markbot is giving an error saying "The website isn't functioning as expected: The contrast of the header's text isn't enough compared to the background-color - double-check what the header looks like if the image doesn't show". 

I've tried black text on a white background and that doesn't even work. 
Please help! 

@hellachella @JessJodoin

**Comment by hellachella** [comment]
Looking into it

**Comment by hellachella** [comment]
Ok I see it

What yours looks like:
![Screen Shot 2020-10-14 at 10 13 38 AM](https://user-images.githubusercontent.com/10465921/96001455-0b78f080-0e06-11eb-825a-af2327cdf30c.png)

What is should look like: 
![Screen Shot 2020-10-14 at 10 13 43 AM](https://user-images.githubusercontent.com/10465921/96001493-16cc1c00-0e06-11eb-8d75-3e9a6404c206.png)

**Comment by tchi0007** [comment]
I think the line 

article div :first-child::first-line {
  color: #1e7c74;
  font-style: italic;
}

is overwriting my h1

**Comment by JessJodoin** [comment]
If you leave that and change the `<div>` surrounding the `<h1>` and `<h2>` to an `<hgroup>` that will fix that issue 😄
